name: 3drr-lowlight
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pyyaml
  - omegaconf
  - tqdm
  - numpy
  - pillow
  - ninja
  - jaxtyping
  - rich
  - packaging
  - setuptools
  - wheel
  - pip:
      - gsplat
